# Generated by Django 3.2.5 on 2021-07-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['artist'],
            },
        ),
        migrations.AlterModelOptions(
            name='albums',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='albums.artist'),
        ),
    ]
