# Generated by Django 3.2.5 on 2021-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='Year_Released',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
